version: '{build}'

clone_depth: 5

cache:
    - x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
    - i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z

environment:
    CTEST_OUTPUT_ON_FAILURE: 1
    matrix:
        - MINGW_DIR: mingw64
          MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-win32/seh/x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z/download
          MINGW_ARCHIVE: x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
          WINDBG_DIR: '%ProgramFiles(x86)%\Windows Kits\8.1\Debuggers\x64'
        - MINGW_DIR: mingw32
          MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.9.2/threads-win32/dwarf/i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z/download
          MINGW_ARCHIVE: i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z
          WINDBG_DIR: '%ProgramFiles(x86)%\Windows Kits\8.1\Debuggers\x86'

before_build:
    - set Path=%CD%\%MINGW_DIR%\bin;%Path%
    - g++ --version
    - mingw32-make --version
    - cmake --version
    - echo "NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%"
    - ps: (Get-Item "${Env:WINDBG_DIR}\dbghelp.dll").VersionInfo
    - if "%APPVEYOR_REPO_TAG%"=="true" (set CMAKE_BUILD_TYPE=Release) else (set CMAKE_BUILD_TYPE=Debug)
    - set ENABLE_COVERAGE=yes
    - if "%APPVEYOR_REPO_TAG%"=="true" set ENABLE_COVERAGE=no
    - if NOT "%MINGW_DIR%"=="mingw64" set ENABLE_COVERAGE=no
    - cmake -H. -Bbuild\mingw -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -DENABLE_COVERAGE=%ENABLE_COVERAGE% -DWINDBG_DIR="%WINDBG_DIR%"

build_script:
    - cmake --build build\mingw --use-stderr --target all -- -j%NUMBER_OF_PROCESSORS%

